### ISSUE TITLE
How do I use SweetJS and ES6 in the same project?

### ISSUE THREAD

**Issue by metaraine** [mozilla/sweet.js#473] opened 2015-05-23 02:40 UTC
How do I use SweetJS and ES6 in the same project? If it's not supported, is there an intention for supporting this integration? Or alternatives suggested?

I was attempting to use ES6 template strings in my project, and sweetjs choked.
http://sweetjs.org/browser/editor.html#var%20a%20=%20%60test%60

I found tangential answers in Issues and googling, but nothing really satisfactory in the form of a terse explanation of this compatibility question. Thanks!

**Comment by disnet** [comment] 2015-05-23 16:59
That looks like a regression. Template literals should be working.

**Comment by disnet** [comment] 2016-03-28 01:40
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.

**Closed by disnet** 2016-03-28 01:40 UTC
