### ISSUE TITLE
Can't match { as literal

### ISSUE THREAD

**Issue by dfoverdx** [mozilla/sweet.js#458] opened 2015-03-10 00:27 UTC
Unless the closing brace '}' is inside the literal with the opening brace, things fall apart.

    macro m {
        case { $[{ hello }] $a } => { return #{ console.log($a); }; }
    }

    m { hello } foo

    // compiles to:
    console.log(foo);

    /************************/

    macro m {
        case { $[{] $a $[}] } => { return #{ console.log($a); }; }
    }

    // things happen that I don't understand
    // error: 
    // Unexpected end of input
    // [... ) ( )  ...]
    m { foo }

For what it's worth, matching only a closing brace works fine.

**Comment by disnet** [comment] 2015-03-10 00:36
This is (mostly) expected behavior. The reader (which runs before any macros are loaded) does delimiter matching so the error you are getting is basically saying "I expected a closing brace before running out of input". The macro literal syntax can't help us here because the matching happens at an earlier stage.

There is a small bug in that the unmatched closing brace should also throw an error.

You might be able to work around this by abusing [read tables](http://sweetjs.org/doc/main/sweet.html#reader-extensions) but why do you need to put the braces in a literal? Would the pattern `{ $a }` work just fine?

**Comment by dfoverdx** [comment] 2015-03-10 00:45
I'm trying to write a c# style anonymous function syntax macro.

    (foo) => foo + 1;

becomes

    function (foo) { return foo + 1; }

But if the right side has braces around it, I don't want to add the "return".

    (foo) => { 
        foo += 1;
        alert(foo);
    }

becomes

    function (foo) {
        foo +=1;
        alert(foo);
    }

The code I wrote is:

    // define c#-style anonymous function syntax
    macro (=>) {
        case infix { ($params:($p (,) ...)) | _ { $body:($line:expr (;) ...) } } => { 
            return #{ function ($params) { $body } }; 
        }
        case infix { ($params:($p (,) ...)) | _ $body:expr } => {
            return #{ function ($params) { return $body };
        }
    }

    var x = (a) => { 
        a += 1;
        alert(a);
    }
    
    x(1);
    
    var y = (a) => a + 1;
    alert(y(1));

It's having issues.  I thought maybe if I escaped the braces, it would work, but that's not the case.

**Comment by disnet** [comment] 2015-03-10 00:49
That seems to work actually. You're just missing a closing brace in the body of your second case ;)

**Comment by dfoverdx** [comment] 2015-03-10 00:49
Just realized that myself.  Thanks!

**Closed** 2015-03-10 00:54 UTC
