### ISSUE TITLE
INVALID MAPPING: error

### ISSUE THREAD

**Issue by jasuperior** [mozilla/sweet.js#486] opened 2015-08-11 06:37 UTC
whenever i try to expand my macro file with --sourcemaps or -c, i get the following error 
```
C:\Users\Jamel\AppData\Roaming\npm\node_modules\sweet.js\node_modules\escodegen\node_modules\source-map\lib\source-map\source-map-generator.js:275
        throw new Error('Invalid mapping: ' + JSON.stringify({
              ^
Error: Invalid mapping: {"generated":{"line":636,"column":72},"source":"C:\\Users\\Jamel\\Documents\\My Programs\\SMPL\\test.smpl","original":{"line":688,"column":-4089},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (C:\Users\Jamel\AppData\Roaming\npm\node_modules\sweet.js\node_modules\escodegen\node_modules\source-map\lib\source-map\source-map-generator.js:275:15)
    at SourceMapGenerator_addMapping [as addMapping] (C:\Users\Jamel\AppData\Roaming\npm\node_modules\sweet.js\node_modules\escodegen\node_modules\source-map\lib\source-map\source-map-generator.js:105:14)
    at C:\Users\Jamel\AppData\Roaming\npm\node_modules\sweet.js\node_modules\escodegen\node_modules\source-map\lib\source-map\source-node.js:350:15
    at SourceNode_walk [as walk] (C:\Users\Jamel\AppData\Roaming\npm\node_modules\sweet.js\node_modules\escodegen\node_modules\source-map\lib\source-map\source-node.js:229:11)
    at SourceNode_walk [as walk] (C:\Users\Jamel\AppData\Roaming\npm\node_modules\sweet.js\node_modules\escodegen\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\Users\Jamel\AppData\Roaming\npm\node_modules\sweet.js\node_modules\escodegen\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\Users\Jamel\AppData\Roaming\npm\node_modules\sweet.js\node_modules\escodegen\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\Users\Jamel\AppData\Roaming\npm\node_modules\sweet.js\node_modules\escodegen\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\Users\Jamel\AppData\Roaming\npm\node_modules\sweet.js\node_modules\escodegen\node_modules\source-map\lib\source-map\source-node.js:225:15)
    at SourceNode_walk [as walk] (C:\Users\Jamel\AppData\Roaming\npm\node_modules\sweet.js\node_modules\escodegen\node_modules\source-map\lib\source-map\source-node.js:225:15)
[Finished in 6.2s]
```
It seems to only be a problem with sourcemaps, because i can produce the expanded js file just fine without them. Also, its probably also best that i note that, sourcemaps were working just yesterday for me. so something is up... anyone that can help, i would appreciate.

**Comment by disnet** [comment] 2015-08-12 21:00
Are you using a npm version or from master? Do you happen to have a small reproducible snippet?

**Comment by disnet** [comment] 2016-03-28 01:41
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.

**Closed by disnet** 2016-03-28 01:41 UTC
