### ISSUE TITLE
Comment Bug

### ISSUE THREAD

**Issue by cktaylor** [mozilla/sweet.js#464] opened 2015-03-23 19:06 UTC
Hi, after updating from 0.7.3 to 0.7.4 I noticed a bug that was mangling return statements if preceded by a comment.

sweetjs@0.7.4 now turns this:
```javascript
window.x = function() {
    // Used to exhibit breaking behavior introduced in 0.7.4
    return parseInt(window.innerWidth, 10);
};
```

into this:
```javascript
window.x = function () {
    return // Used to exhibit breaking behavior introduced in 0.7.4
    parseInt(window.innerWidth, 10);
};
```

**Comment by cktaylor** [comment] 2015-03-23 19:07
After looking through the commits that went into 0.7.4, looks like its a bug with escodegen that you were already aware of.

https://github.com/mozilla/sweet.js/commit/274ee53d7f444068a0564d63572d1465d65550ca

**Comment by levjj** [comment] 2015-04-05 00:07
I've also encountered this bug.  It seems the only way to find it is by carefully reading the generated code.  It's not ideal but a possible work-around is to delete all your comments when using sweet.js.

**Comment by stuartZhang** [comment] 2015-11-11 07:17
I have stumbled across the same bug at the 0.7.4 version. As yet, I have to revert back to  0.7.3 which is without the issue.

**Comment by stuartZhang** [comment] 2015-11-11 07:20
var // After the sweetjs compilation
variableName = 'test';

The assignment statement can still work.

However, 

return // After the sweetjs compilation
'test';

The return statement always return undefined.

It brings about the business-logic error in my application program.

**Comment by sorawee** [comment] 2016-01-08 22:34
It's been almost a year. Is there any fix? If not, is it possible to write a warning message saying that 0.7.4 is not functional correctly? This bug seems pretty severe to me.

**Comment by disnet** [comment] 2016-01-11 18:28
Sorry not yet. I've been putting all my spare time into the redesign #485.

**Comment by domenic** [comment] 2016-02-17 22:35
It would be really helpful to get this fixed. I have run into it on my own projects. Is @levjj's https://github.com/levjj/sweet.js/commit/d96abc364968a2598ace65c5458d3b75c3acf748 the only thing needed?

**Comment by domenic** [comment] 2016-02-17 22:56
Oh, I see, @levjj's commit was a workaround, not a fix :(

**Comment by disnet** [comment] 2016-02-17 22:58
Yeah, not a fix. 

Sorry for the long delay on this. I'll try to take a look this week.

**Comment by domenic** [comment] 2016-02-17 23:15
Thank you! That would be much appreciated. I was very excited to find SweetJS as a probably solution for my woes, but when trying to run it over a larger codebase, this issue is breaking pretty much everything.

I *believe* I've confirmed by local hacking that blindly updating escodegen and escope does not solve the issue.

**Comment by disnet** [comment] 2016-02-18 06:45
Ok, fixed the bug, sort of. It was in the comment handling of our forked version of esprima (the fork happend back when their comment handling code was a bit gnarly).

This fix is really just a hack around comments in return statements specifically, not a general fix for comment handling. This should be enough to prevent badly behaved comments from changing the semantics of your program but there are probably lingering bugs around exactly where comments show up in the ast. The general fix (replaying the work done in esprima) is probably not worth it since the [redesign](https://github.com/mozilla/sweet.js/pull/485) will obviate all this code. 

Closing this issue but feel free to reopen if you notice any other cases I missed.

**Closed by disnet** 2016-02-18 06:45 UTC

**Comment by domenic** [comment] 2016-02-18 15:22
I also noticed it with throw statements. I haven't tested yet, but I'd imagine looking at the above commit that it also needs to be applied similarly?

**Comment by disnet** [comment] 2016-02-18 17:11
Ah yes, throws are a problem too. Just pushed the same fix. Thanks!
